//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
[System.Xml.Serialization.XmlRootAttribute("A2A", Namespace="http://Mindbus.nl/A2A", IsNullable=false)]
public partial class A2AType {
    
    private ctPerson[] personField;
    
    private ctEvent[] eventField;
    
    private ctObject[] objectField;
    
    private ctRelationEP[] relationEPField;
    
    private ctRelationPP[] relationPPField;
    
    private ctRelationPO[] relationPOField;
    
    private ctRelationEO[] relationEOField;
    
    private ctRelationP[] relationPField;
    
    private ctRelationOO[] relationOOField;
    
    private ctRelationO[] relationOField;
    
    private ctSource sourceField;
    
    private stVersion versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Person")]
    public ctPerson[] Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Event")]
    public ctEvent[] Event {
        get {
            return this.eventField;
        }
        set {
            this.eventField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Object")]
    public ctObject[] Object {
        get {
            return this.objectField;
        }
        set {
            this.objectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelationEP")]
    public ctRelationEP[] RelationEP {
        get {
            return this.relationEPField;
        }
        set {
            this.relationEPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelationPP")]
    public ctRelationPP[] RelationPP {
        get {
            return this.relationPPField;
        }
        set {
            this.relationPPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelationPO")]
    public ctRelationPO[] RelationPO {
        get {
            return this.relationPOField;
        }
        set {
            this.relationPOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelationEO")]
    public ctRelationEO[] RelationEO {
        get {
            return this.relationEOField;
        }
        set {
            this.relationEOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelationP")]
    public ctRelationP[] RelationP {
        get {
            return this.relationPField;
        }
        set {
            this.relationPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelationOO")]
    public ctRelationOO[] RelationOO {
        get {
            return this.relationOOField;
        }
        set {
            this.relationOOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelationO")]
    public ctRelationO[] RelationO {
        get {
            return this.relationOField;
        }
        set {
            this.relationOField = value;
        }
    }
    
    /// <remarks/>
    public ctSource Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public stVersion Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctPerson {
    
    private ctPersonName personNameField;
    
    private string genderField;
    
    private ctDetailPlace residenceField;
    
    private ctPersonReligion religionField;
    
    private ctDetailPlace originField;
    
    private ctPersonAge ageField;
    
    private ctTransDate birthDateField;
    
    private ctDetailPlace birthPlaceField;
    
    private ctTransString[] professionField;
    
    private string maritalStatusField;
    
    private ctRemarkPair[] personRemarkField;
    
    private string pidField;
    
    /// <remarks/>
    public ctPersonName PersonName {
        get {
            return this.personNameField;
        }
        set {
            this.personNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    public ctDetailPlace Residence {
        get {
            return this.residenceField;
        }
        set {
            this.residenceField = value;
        }
    }
    
    /// <remarks/>
    public ctPersonReligion Religion {
        get {
            return this.religionField;
        }
        set {
            this.religionField = value;
        }
    }
    
    /// <remarks/>
    public ctDetailPlace Origin {
        get {
            return this.originField;
        }
        set {
            this.originField = value;
        }
    }
    
    /// <remarks/>
    public ctPersonAge Age {
        get {
            return this.ageField;
        }
        set {
            this.ageField = value;
        }
    }
    
    /// <remarks/>
    public ctTransDate BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
    
    /// <remarks/>
    public ctDetailPlace BirthPlace {
        get {
            return this.birthPlaceField;
        }
        set {
            this.birthPlaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Profession")]
    public ctTransString[] Profession {
        get {
            return this.professionField;
        }
        set {
            this.professionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string MaritalStatus {
        get {
            return this.maritalStatusField;
        }
        set {
            this.maritalStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PersonRemark")]
    public ctRemarkPair[] PersonRemark {
        get {
            return this.personRemarkField;
        }
        set {
            this.personRemarkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string pid {
        get {
            return this.pidField;
        }
        set {
            this.pidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctPersonName {
    
    private ctTransLongString personNameLiteralField;
    
    private ctTransString personNameTitleField;
    
    private ctTransString personNameTitleOfNobilityField;
    
    private ctTransString personNameFirstNameField;
    
    private ctTransString personNameNickNameField;
    
    private ctTransString personNameAliasField;
    
    private ctTransString personNamePatronymField;
    
    private ctTransString personNamePrefixLastNameField;
    
    private ctTransString personNameLastNameField;
    
    private ctTransString personNameFamilyNameField;
    
    private ctTransString personNameInitialsField;
    
    private ctRemarkPair[] personNameRemarkField;
    
    /// <remarks/>
    public ctTransLongString PersonNameLiteral {
        get {
            return this.personNameLiteralField;
        }
        set {
            this.personNameLiteralField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString PersonNameTitle {
        get {
            return this.personNameTitleField;
        }
        set {
            this.personNameTitleField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString PersonNameTitleOfNobility {
        get {
            return this.personNameTitleOfNobilityField;
        }
        set {
            this.personNameTitleOfNobilityField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString PersonNameFirstName {
        get {
            return this.personNameFirstNameField;
        }
        set {
            this.personNameFirstNameField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString PersonNameNickName {
        get {
            return this.personNameNickNameField;
        }
        set {
            this.personNameNickNameField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString PersonNameAlias {
        get {
            return this.personNameAliasField;
        }
        set {
            this.personNameAliasField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString PersonNamePatronym {
        get {
            return this.personNamePatronymField;
        }
        set {
            this.personNamePatronymField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString PersonNamePrefixLastName {
        get {
            return this.personNamePrefixLastNameField;
        }
        set {
            this.personNamePrefixLastNameField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString PersonNameLastName {
        get {
            return this.personNameLastNameField;
        }
        set {
            this.personNameLastNameField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString PersonNameFamilyName {
        get {
            return this.personNameFamilyNameField;
        }
        set {
            this.personNameFamilyNameField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString PersonNameInitials {
        get {
            return this.personNameInitialsField;
        }
        set {
            this.personNameInitialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PersonNameRemark")]
    public ctRemarkPair[] PersonNameRemark {
        get {
            return this.personNameRemarkField;
        }
        set {
            this.personNameRemarkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctTransLongString {
    
    private string transcriptionRemarkField;
    
    private string languageField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string TranscriptionRemark {
        get {
            return this.transcriptionRemarkField;
        }
        set {
            this.transcriptionRemarkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctScan {
    
    private ushort orderSequenceNumberField;
    
    private bool orderSequenceNumberFieldSpecified;
    
    private string uriField;
    
    private string uriViewerField;
    
    private string uriPreviewField;
    
    /// <remarks/>
    public ushort OrderSequenceNumber {
        get {
            return this.orderSequenceNumberField;
        }
        set {
            this.orderSequenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderSequenceNumberSpecified {
        get {
            return this.orderSequenceNumberFieldSpecified;
        }
        set {
            this.orderSequenceNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string Uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string UriViewer {
        get {
            return this.uriViewerField;
        }
        set {
            this.uriViewerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string UriPreview {
        get {
            return this.uriPreviewField;
        }
        set {
            this.uriPreviewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctSourceReference {
    
    private string placeField;
    
    private string institutionNameField;
    
    private string archiveField;
    
    private string collectionField;
    
    private string sectionField;
    
    private string bookField;
    
    private string folioField;
    
    private string rolodeckField;
    
    private string stackField;
    
    private string registryNumberField;
    
    private string documentNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string InstitutionName {
        get {
            return this.institutionNameField;
        }
        set {
            this.institutionNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Archive {
        get {
            return this.archiveField;
        }
        set {
            this.archiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Collection {
        get {
            return this.collectionField;
        }
        set {
            this.collectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Section {
        get {
            return this.sectionField;
        }
        set {
            this.sectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Book {
        get {
            return this.bookField;
        }
        set {
            this.bookField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Folio {
        get {
            return this.folioField;
        }
        set {
            this.folioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Rolodeck {
        get {
            return this.rolodeckField;
        }
        set {
            this.rolodeckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Stack {
        get {
            return this.stackField;
        }
        set {
            this.stackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string RegistryNumber {
        get {
            return this.registryNumberField;
        }
        set {
            this.registryNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string DocumentNumber {
        get {
            return this.documentNumberField;
        }
        set {
            this.documentNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctEac {
    
    private object itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("Code", typeof(string), DataType="token")]
    [System.Xml.Serialization.XmlElementAttribute("URL", typeof(string), DataType="anyURI")]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    Code,
    
    /// <remarks/>
    URL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctEad {
    
    private object itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("Code", typeof(string), DataType="token")]
    [System.Xml.Serialization.XmlElementAttribute("URL", typeof(string), DataType="anyURI")]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    Code,
    
    /// <remarks/>
    URL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctIndexDate {
    
    private System.DateTime fromField;
    
    private System.DateTime toField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime From {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime To {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctPlace {
    
    private ctTransString countryField;
    
    private ctTransString provinceField;
    
    private ctTransString stateField;
    
    private ctTransString placeField;
    
    /// <remarks/>
    public ctTransString Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString Province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString Place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctTransString {
    
    private string transcriptionRemarkField;
    
    private string languageField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string TranscriptionRemark {
        get {
            return this.transcriptionRemarkField;
        }
        set {
            this.transcriptionRemarkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctSource {
    
    private ctPlace sourcePlaceField;
    
    private ctIndexDate sourceIndexDateField;
    
    private ctTransDate sourceDateField;
    
    private string sourceTypeField;
    
    private ctEad eADField;
    
    private ctEac eACField;
    
    private ctSourceReference sourceReferenceField;
    
    private ctScan[] sourceAvailableScansField;
    
    private System.DateTime sourceDigitalizationDateField;
    
    private bool sourceDigitalizationDateFieldSpecified;
    
    private System.DateTime sourceLastChangeDateField;
    
    private bool sourceLastChangeDateFieldSpecified;
    
    private string sourceDigitalOriginalField;
    
    private string recordIdentifierField;
    
    private string recordGUIDField;
    
    private ctRemarkPair[] sourceRemarkField;
    
    /// <remarks/>
    public ctPlace SourcePlace {
        get {
            return this.sourcePlaceField;
        }
        set {
            this.sourcePlaceField = value;
        }
    }
    
    /// <remarks/>
    public ctIndexDate SourceIndexDate {
        get {
            return this.sourceIndexDateField;
        }
        set {
            this.sourceIndexDateField = value;
        }
    }
    
    /// <remarks/>
    public ctTransDate SourceDate {
        get {
            return this.sourceDateField;
        }
        set {
            this.sourceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string SourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
    
    /// <remarks/>
    public ctEad EAD {
        get {
            return this.eADField;
        }
        set {
            this.eADField = value;
        }
    }
    
    /// <remarks/>
    public ctEac EAC {
        get {
            return this.eACField;
        }
        set {
            this.eACField = value;
        }
    }
    
    /// <remarks/>
    public ctSourceReference SourceReference {
        get {
            return this.sourceReferenceField;
        }
        set {
            this.sourceReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Scan", IsNullable=false)]
    public ctScan[] SourceAvailableScans {
        get {
            return this.sourceAvailableScansField;
        }
        set {
            this.sourceAvailableScansField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime SourceDigitalizationDate {
        get {
            return this.sourceDigitalizationDateField;
        }
        set {
            this.sourceDigitalizationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SourceDigitalizationDateSpecified {
        get {
            return this.sourceDigitalizationDateFieldSpecified;
        }
        set {
            this.sourceDigitalizationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime SourceLastChangeDate {
        get {
            return this.sourceLastChangeDateField;
        }
        set {
            this.sourceLastChangeDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SourceLastChangeDateSpecified {
        get {
            return this.sourceLastChangeDateFieldSpecified;
        }
        set {
            this.sourceLastChangeDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string SourceDigitalOriginal {
        get {
            return this.sourceDigitalOriginalField;
        }
        set {
            this.sourceDigitalOriginalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string RecordIdentifier {
        get {
            return this.recordIdentifierField;
        }
        set {
            this.recordIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string RecordGUID {
        get {
            return this.recordGUIDField;
        }
        set {
            this.recordGUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SourceRemark")]
    public ctRemarkPair[] SourceRemark {
        get {
            return this.sourceRemarkField;
        }
        set {
            this.sourceRemarkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctTransDate {
    
    private ctTransLongString literalDateField;
    
    private ctTransNumber yearField;
    
    private ctTransNumber monthField;
    
    private ctTransNumber dayField;
    
    private ctTransNumber hourField;
    
    private ctTransNumber minuteField;
    
    private string calendarField;
    
    private System.DateTime indexDateTimeField;
    
    private bool indexDateTimeFieldSpecified;
    
    /// <remarks/>
    public ctTransLongString LiteralDate {
        get {
            return this.literalDateField;
        }
        set {
            this.literalDateField = value;
        }
    }
    
    /// <remarks/>
    public ctTransNumber Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public ctTransNumber Month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
    
    /// <remarks/>
    public ctTransNumber Day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
    
    /// <remarks/>
    public ctTransNumber Hour {
        get {
            return this.hourField;
        }
        set {
            this.hourField = value;
        }
    }
    
    /// <remarks/>
    public ctTransNumber Minute {
        get {
            return this.minuteField;
        }
        set {
            this.minuteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string Calendar {
        get {
            return this.calendarField;
        }
        set {
            this.calendarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime IndexDateTime {
        get {
            return this.indexDateTimeField;
        }
        set {
            this.indexDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IndexDateTimeSpecified {
        get {
            return this.indexDateTimeFieldSpecified;
        }
        set {
            this.indexDateTimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctTransNumber {
    
    private string transcriptionRemarkField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string TranscriptionRemark {
        get {
            return this.transcriptionRemarkField;
        }
        set {
            this.transcriptionRemarkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctRemarkPair {
    
    private ctTransLongString valueField;
    
    private string keyField;
    
    /// <remarks/>
    public ctTransLongString Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctRelationO {
    
    private string objectKeyRefField;
    
    private string relationTypeField;
    
    private ctTransString extendedRelationTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ObjectKeyRef {
        get {
            return this.objectKeyRefField;
        }
        set {
            this.objectKeyRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string RelationType {
        get {
            return this.relationTypeField;
        }
        set {
            this.relationTypeField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString ExtendedRelationType {
        get {
            return this.extendedRelationTypeField;
        }
        set {
            this.extendedRelationTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctRelationOO {
    
    private string[] objectKeyRefField;
    
    private string relationTypeField;
    
    private ctTransString extendedRelationTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ObjectKeyRef", DataType="token")]
    public string[] ObjectKeyRef {
        get {
            return this.objectKeyRefField;
        }
        set {
            this.objectKeyRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string RelationType {
        get {
            return this.relationTypeField;
        }
        set {
            this.relationTypeField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString ExtendedRelationType {
        get {
            return this.extendedRelationTypeField;
        }
        set {
            this.extendedRelationTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctRelationP {
    
    private string personKeyRefField;
    
    private string relationTypeField;
    
    private ctTransString extendedRelationTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string PersonKeyRef {
        get {
            return this.personKeyRefField;
        }
        set {
            this.personKeyRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string RelationType {
        get {
            return this.relationTypeField;
        }
        set {
            this.relationTypeField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString ExtendedRelationType {
        get {
            return this.extendedRelationTypeField;
        }
        set {
            this.extendedRelationTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctRelationEO {
    
    private string eventKeyRefField;
    
    private string objectKeyRefField;
    
    private string relationTypeField;
    
    private ctTransString extendedRelationTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string EventKeyRef {
        get {
            return this.eventKeyRefField;
        }
        set {
            this.eventKeyRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ObjectKeyRef {
        get {
            return this.objectKeyRefField;
        }
        set {
            this.objectKeyRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string RelationType {
        get {
            return this.relationTypeField;
        }
        set {
            this.relationTypeField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString ExtendedRelationType {
        get {
            return this.extendedRelationTypeField;
        }
        set {
            this.extendedRelationTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctRelationPO {
    
    private string personKeyRefField;
    
    private string objectKeyRefField;
    
    private string relationTypeField;
    
    private ctTransString extendedRelationTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string PersonKeyRef {
        get {
            return this.personKeyRefField;
        }
        set {
            this.personKeyRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string ObjectKeyRef {
        get {
            return this.objectKeyRefField;
        }
        set {
            this.objectKeyRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string RelationType {
        get {
            return this.relationTypeField;
        }
        set {
            this.relationTypeField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString ExtendedRelationType {
        get {
            return this.extendedRelationTypeField;
        }
        set {
            this.extendedRelationTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctRelationPP {
    
    private string[] personKeyRefField;
    
    private string relationTypeField;
    
    private ctTransString extendedRelationTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PersonKeyRef", DataType="token")]
    public string[] PersonKeyRef {
        get {
            return this.personKeyRefField;
        }
        set {
            this.personKeyRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string RelationType {
        get {
            return this.relationTypeField;
        }
        set {
            this.relationTypeField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString ExtendedRelationType {
        get {
            return this.extendedRelationTypeField;
        }
        set {
            this.extendedRelationTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctRelationEP {
    
    private string personKeyRefField;
    
    private string eventKeyRefField;
    
    private string relationTypeField;
    
    private ctTransString extendedRelationTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string PersonKeyRef {
        get {
            return this.personKeyRefField;
        }
        set {
            this.personKeyRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string EventKeyRef {
        get {
            return this.eventKeyRefField;
        }
        set {
            this.eventKeyRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string RelationType {
        get {
            return this.relationTypeField;
        }
        set {
            this.relationTypeField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString ExtendedRelationType {
        get {
            return this.extendedRelationTypeField;
        }
        set {
            this.extendedRelationTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctObject {
    
    private string descriptionField;
    
    private ctRemarkPair[] objectRemarkField;
    
    private string oidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ObjectRemark")]
    public ctRemarkPair[] ObjectRemark {
        get {
            return this.objectRemarkField;
        }
        set {
            this.objectRemarkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string oid {
        get {
            return this.oidField;
        }
        set {
            this.oidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctReligion {
    
    private ctTransString religionLiteralField;
    
    /// <remarks/>
    public ctTransString ReligionLiteral {
        get {
            return this.religionLiteralField;
        }
        set {
            this.religionLiteralField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctEvent {
    
    private string eventTypeField;
    
    private ctTransDate eventDateField;
    
    private ctDetailPlace eventPlaceField;
    
    private ctReligion eventReligionField;
    
    private ctRemarkPair[] eventRemarkField;
    
    private string eidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string EventType {
        get {
            return this.eventTypeField;
        }
        set {
            this.eventTypeField = value;
        }
    }
    
    /// <remarks/>
    public ctTransDate EventDate {
        get {
            return this.eventDateField;
        }
        set {
            this.eventDateField = value;
        }
    }
    
    /// <remarks/>
    public ctDetailPlace EventPlace {
        get {
            return this.eventPlaceField;
        }
        set {
            this.eventPlaceField = value;
        }
    }
    
    /// <remarks/>
    public ctReligion EventReligion {
        get {
            return this.eventReligionField;
        }
        set {
            this.eventReligionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EventRemark")]
    public ctRemarkPair[] EventRemark {
        get {
            return this.eventRemarkField;
        }
        set {
            this.eventRemarkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string eid {
        get {
            return this.eidField;
        }
        set {
            this.eidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctDetailPlace {
    
    private ctTransString countryField;
    
    private ctTransString provinceField;
    
    private ctTransString stateField;
    
    private ctTransString countyField;
    
    private ctTransString placeField;
    
    private ctTransString municipalityField;
    
    private ctTransString partMunicipalityField;
    
    private ctTransString blockField;
    
    private ctTransString quarterField;
    
    private ctTransString streetField;
    
    private ctTransString descriptiveLocationIndicatorField;
    
    private ctTransString houseNameField;
    
    private ctTransString houseNumberField;
    
    private ctTransString houseNumberAdditionField;
    
    private ctTransString longitudeField;
    
    private ctTransString latitudeField;
    
    private ctRemarkPair[] detailPlaceRemarkField;
    
    /// <remarks/>
    public ctTransString Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString Province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString County {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString Place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString Municipality {
        get {
            return this.municipalityField;
        }
        set {
            this.municipalityField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString PartMunicipality {
        get {
            return this.partMunicipalityField;
        }
        set {
            this.partMunicipalityField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString Block {
        get {
            return this.blockField;
        }
        set {
            this.blockField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString Quarter {
        get {
            return this.quarterField;
        }
        set {
            this.quarterField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString DescriptiveLocationIndicator {
        get {
            return this.descriptiveLocationIndicatorField;
        }
        set {
            this.descriptiveLocationIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString HouseName {
        get {
            return this.houseNameField;
        }
        set {
            this.houseNameField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString HouseNumber {
        get {
            return this.houseNumberField;
        }
        set {
            this.houseNumberField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString HouseNumberAddition {
        get {
            return this.houseNumberAdditionField;
        }
        set {
            this.houseNumberAdditionField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString Longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    public ctTransString Latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DetailPlaceRemark")]
    public ctRemarkPair[] DetailPlaceRemark {
        get {
            return this.detailPlaceRemarkField;
        }
        set {
            this.detailPlaceRemarkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctPersonAge {
    
    private ctTransLongString personAgeLiteralField;
    
    private ctTransNumber personAgeYearsField;
    
    private ctTransNumber personAgeMonthsField;
    
    private ctTransNumber personAgeWeeksField;
    
    private ctTransNumber personAgeDaysField;
    
    private ctTransNumber personAgeHoursField;
    
    private ctTransNumber personAgeMinutesField;
    
    /// <remarks/>
    public ctTransLongString PersonAgeLiteral {
        get {
            return this.personAgeLiteralField;
        }
        set {
            this.personAgeLiteralField = value;
        }
    }
    
    /// <remarks/>
    public ctTransNumber PersonAgeYears {
        get {
            return this.personAgeYearsField;
        }
        set {
            this.personAgeYearsField = value;
        }
    }
    
    /// <remarks/>
    public ctTransNumber PersonAgeMonths {
        get {
            return this.personAgeMonthsField;
        }
        set {
            this.personAgeMonthsField = value;
        }
    }
    
    /// <remarks/>
    public ctTransNumber PersonAgeWeeks {
        get {
            return this.personAgeWeeksField;
        }
        set {
            this.personAgeWeeksField = value;
        }
    }
    
    /// <remarks/>
    public ctTransNumber PersonAgeDays {
        get {
            return this.personAgeDaysField;
        }
        set {
            this.personAgeDaysField = value;
        }
    }
    
    /// <remarks/>
    public ctTransNumber PersonAgeHours {
        get {
            return this.personAgeHoursField;
        }
        set {
            this.personAgeHoursField = value;
        }
    }
    
    /// <remarks/>
    public ctTransNumber PersonAgeMinutes {
        get {
            return this.personAgeMinutesField;
        }
        set {
            this.personAgeMinutesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public partial class ctPersonReligion {
    
    private ctTransString personReligionLiteralField;
    
    /// <remarks/>
    public ctTransString PersonReligionLiteral {
        get {
            return this.personReligionLiteralField;
        }
        set {
            this.personReligionLiteralField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Mindbus.nl/A2A")]
public enum stVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.7")]
    Item17,
}
